-- Users table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(50) NOT NULL
);

-- Recipes table
CREATE TABLE recipes (
    recipe_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500)
);

ALTER TABLE recipes MODIFY description VARCHAR2(2000);

-- Ingredients table
CREATE TABLE ingredients (
    ingredient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_name VARCHAR2(100) NOT NULL
);

-- Junction table linking recipes and ingredients
CREATE TABLE recipe_ingredients (
    recipe_id NUMBER REFERENCES recipes(recipe_id),
    ingredient_id NUMBER REFERENCES ingredients(ingredient_id),
    quantity VARCHAR2(50),
    PRIMARY KEY (recipe_id, ingredient_id)
);


ALTER TABLE recipe_ingredients ADD ingredient_name VARCHAR2(100);

-- Favorites / Likes table
CREATE TABLE favorites (
    fav_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(user_id),
    recipe_id NUMBER REFERENCES recipes(recipe_id)
);

-- Reviews table
CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id NUMBER REFERENCES recipes(recipe_id),
    user_id NUMBER REFERENCES users(user_id),
    rating NUMBER CHECK (rating BETWEEN 1 AND 5),
    "comment" VARCHAR2(500)
);

CREATE TABLE recipe_steps (
    step_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id NUMBER REFERENCES recipes(recipe_id) ON DELETE CASCADE,
    step_number NUMBER NOT NULL,
    step_description VARCHAR2(1000) NOT NULL
);
